### ISSUE TITLE
ConfigHelper.getSegment()这个方法有bug吧

### ISSUE THREAD

**Issue by zzl221000** [AnyListen/elasticsearch-analysis-hanlp#2]
`
 if ("crf".equals(algorithm) || "条件随机场".equals(algorithm) ||
                    "perceptron".equals(algorithm) || "感知机".equals(algorithm)) {
                if (HanLP.Config.IOAdapter instanceof ResourceIOAdapter) {
                    return null;
                }
            }
`
这个应该是启动es会调用的方法吧，return null ，之后调crf和perceptron都会报npe

**Comment by AnyListen** [comment]
因为 ResourceIOAdapter 是肯定不可能包含模型文件的；
如果你需要使用 crf 和感知机分词，那么需要先设置相关词典路径；
这样就不会走这个逻辑了

**Comment by zzl221000** [comment]
不好意思没看到
直接打包的话我这边es提示少了elasticsearch目录，手动加上可以离线安装，但是hanlp配置文件一直提示没有所以一直跑的是精简模式，不会是因为classpath没配置当前目录吧

**Comment by AnyListen** [comment]
如果是 6.3 之前的版本请使用 5.X-6.2.X 的分支打包；
自定义词典请参考：https://github.com/AnyListen/elasticsearch-analysis-hanlp#使用自定义词典
