### ISSUE TITLE
hanlp_crf 这个分词器要怎么用，我好像指定分词为“hanlp_crf ”会识别不到，只能用“hanlp”这个分词器

### ISSUE THREAD

**Issue by zhanghuangjie** [AnyListen/elasticsearch-analysis-hanlp#5]
是不是还没有实现呢？

**Comment by AnyListen** [comment]
默认使用的是简版的词典，所以没有 CRF 的模式加载会失败
请参考：https://github.com/AnyListen/elasticsearch-analysis-hanlp#使用自定义词典
来配置完整版的词典，这样就可用使用 CRF 模式了
